<br /><br />

<?php
$meses =
    [
        '01' => 'Janeiro',
        '02' => 'Fevereiro',
        '03' => 'Março',
        '04' => 'Abril',
        '05' => 'Maio',
        '06' => 'Junho',
        '07' => 'Julho',
        '08' => 'Agosto',
        '09' => 'Setembro',
        '10' => 'Outubro',
        '11' => 'Novembro',
        '12' => 'Dezembro'
    ];
?>

<div id="view-content">
    <div class="col-md-6">
        <div class="card card-outline-secondary">
            <div class="card-header">
                <h3 class="mb-0">Cadastro de Pacientes</h3>
            </div>
            <div class="card-body">
                <!-- CADASTRO DE PACIENTES INICIO -->
                <form class="form" role="form" autocomplete="off" action="/pessoa/adicionar" method="post">
                    <div class="form-group row">
                        <label class="col-lg-3 col-form-label form-control-label">Nome:</label>
                        <div class="col-lg-9">
                            <input name="nome" class="form-control" type="text">
                        </div>
                    </div>

                    <div class="form-group row">
                        <label class="col-lg-3 col-form-label form-control-label">Sexo:</label>
                        <div class="col-lg-9">
                            <select name="sexo" id="sexo" class="form-control" size="0">
                                <option value="m">Masculino</option>
                                <option value="f">Feminino</option>
                            </select>
                        </div>
                    </div>

                    <div class="form-group row">
                        <label class="col-lg-3 col-form-label form-control-label">Data de Nascimento:</label>
                        <div class="col-lg-3">
                            <select name="dia" id="dia" class="form-control" size="0">
                                <?php for($i=01; $i<=31;$i++) {
                                    $n = str_pad($i , 2 , '0' , STR_PAD_LEFT);
                                    echo "<option value=\"$n\">$n</option>";
                                }?>
                            </select>
                        </div>

                        <div class="col-lg-3">
                            <select name="mes" id="mes" class="form-control" size="0">
                                <?php
                                foreach ($meses as $key => $mes) {
                                    echo "<option value=\"$key\">$mes</option>";
                                }
                                ?>
                            </select>
                        </div>

                        <div class="col-lg-3">
                            <select name="ano" id="ano" class="form-control" size="0">
                                <?php for($i=2021; $i>=1901;$i--) {
                                    echo "<option value=\"$i\">$i</option>";
                                }?>
                            </select>
                        </div>
                    </div>

                    <div class="form-group row">
                        <label class="col-lg-3 col-form-label form-control-label">Convênio</label>
                        <div class="col-lg-9">
                            <select name="convenio" id="convenio" class="form-control" size="0">
                                <option value="unimed">UNIMED</option>
                                <option value="sus">SUS</option>
                            </select>
                        </div>
                    </div>

                    <div class="form-group row">
                        <label class="col-lg-3 col-form-label form-control-label"></label>
                        <div class="col-lg-9">
                            <input type="reset" class="btn btn-secondary" value="Cancelar">
                            <input type="submit" class="btn btn-primary" value="Salvar">
                        </div>
                    </div>
                </form>
                <!-- CADASTRO DE PACIENTES FIM -->
            </div>
        </div>
    </div>
</div>
