<br /><br />
<div id="view-content">
    <div class="row">
        <div class="col-12">
            <table class="table table-bordered">
                <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Nome</th>
                    <th scope="col">Sexo</th>
                    <th scope="col">Data de Nascimento</th>
                    <th scope="col">Ações</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <th scope="row">1</th>
                    <td>Fulano de Tal</td>
                    <td>Masculino</td>
                    <td>Data de Nascimento</td>
                    <td>
                        <button type="button" class="btn btn-primary"><i class='bx bxs-eyedropper'></i></button>
                        <button type="button" class="btn btn-success"><i class='bx bx-edit'></i></button>
                        <button type="button" class="btn btn-danger"><i class='bx bx-trash-alt'></i></i></button>
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>
